backend:
  name: git-gateway
  branch: main # Falls dein Branch "master" ist, ändere das hier entsprechend

media_folder: "images/uploads" # Pfad, in dem hochgeladene Medien wie Bilder gespeichert werden
public_folder: "/images/uploads" # Öffentlich zugänglicher Pfad für Bilder

editor:
  preview: true

collections:
  - name: "blog"
    label: "Blog"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Inhalt", name: "body", widget: "markdown" }
      - { label: "Bild", name: "image", widget: "image" }
